### ISSUE TITLE
sxyreact - random crashes

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/fbalpha#108]
title, same bug may exist with sxyreact2.

**Comment by barbudreadmon** [comment]
Could you provide a savestate from before the crash ?

**Comment by arnoldsecret** [comment]
when I tested out, the game works fine, until I got to the continue screen.
[sxyreact.zip](https://github.com/libretro/fbalpha/files/2791736/sxyreact.zip)

**Comment by barbudreadmon** [comment]
Ok, i had some issues reproducing this crash, i think it's happening randomly, here is the trace : 
```
ASAN:DEADLYSIGNAL
=================================================================
==13241==ERROR: AddressSanitizer: SEGV on unknown address 0x7f16b4aa1e90 (pc 0x7f16b728c52e bp 0x0000000005c0 sp 0x7ffe1bf67fd0 T0)
==13241==The signal is caused by a READ memory access.
    #0 0x7f16b728c52d in generate_pcm src/burn/snd/es5506.cpp:733
    #1 0x7f16b728c52d in generate_samples src/burn/snd/es5506.cpp:843
    #2 0x7f16b728c52d in ES5506Update(short*, int) src/burn/snd/es5506.cpp:897
    #3 0x7f16b7f9b659 in DrvFrame src/burn/drv/pst90s/d_ssv.cpp:3764
    #4 0x7f16b71ce96d in BurnDrvFrame src/burn/burn.cpp:740
    #5 0x7f16b863d2f8 in ForceFrameStep src/burner/libretro/libretro.cpp:489
    #6 0x7f16b863f631 in retro_run src/burner/libretro/libretro.cpp:891
    #7 0x556505d34b5f  (/usr/bin/retroarch+0x46b5f)
    #8 0x556505d39fcd  (/usr/bin/retroarch+0x4bfcd)
    #9 0x556505d3391f  (/usr/bin/retroarch+0x4591f)
    #10 0x7f16d21bfae6 in __libc_start_main (/lib64/libc.so.6+0x21ae6)
    #11 0x556505d30859  (/usr/bin/retroarch+0x42859)
```

I also checked the game for misalignment issues and found those : 
```
src/cpu/v60/v60.cpp:156:11: runtime error: load of misaligned address 0x7f16b15347f2 for type 'UINT32', which requires 4 byte alignment
0x7f16b15347f2: note: pointer points here
 ff ff  d6 f3 00 02 e0 00 00 00  00 00 00 00 00 00 d6 f4  00 00 00 00 00 00 00 00  00 00 00 00 00 00
              ^ 
src/burn/drv/pst90s/d_ssv.cpp:3185:19: runtime error: store to misaligned address 0x7f16b4745802 for type 'UINT32', which requires 4 byte alignment
0x7f16b4745802: note: pointer points here
 ff ff  ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00
              ^ 
src/burn/tiles_generic.cpp:189:44: runtime error: load of misaligned address 0x7f16b4745802 for type 'UINT32', which requires 4 byte alignment
0x7f16b4745802: note: pointer points here
 ff ff  ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00
              ^ 
src/cpu/v60/v60.cpp:129:11: runtime error: load of misaligned address 0x7f16b13375cd for type 'UINT16', which requires 2 byte alignment
0x7f16b13375cd: note: pointer points here
 a7 fa ff 7a 06 00 97  44 60 2d 26 e0 2d 46 81  c6 a2 fd ff d6 65 87 20  e0 75 10 00 87 20 e1 75  0a
             ^ 
src/burn/drv/pst90s/d_ssv.cpp:2007:23: runtime error: store to misaligned address 0x7f16b4745802 for type 'UINT32', which requires 4 byte alignment
0x7f16b4745802: note: pointer points here
 ff ff  ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00
```

**Comment by dinkc64** [comment]
the pachinko games in ssv were never finished - now they are :)
please try now - since I can't make it crash on my side (before working on the driver), I need you to let me know if it still crashes.  be sure not to use old savestates, as the savestate format changed for this game!

hooked up the pachinko dial - these games are completely unplayable without this dial, even in "joystick" mode!  make _sure_ you set the dipswitch control mode to Dial after mapping the dial to your gamepad/mouse etc. (of course, reload the game afterwards)

please test :)

**Comment by barbudreadmon** [comment]
@dinkc64 i played a few minutes in fast forward mode (~x10), i couldn't get the crash again, i can't be totally sure considering it was random but the crash might be fixed.

I also noticed some kind of offset (see right side of the screen) on attract mode + sammy screen (the second time it appears) : 
![sxyreact-190125-081420](https://user-images.githubusercontent.com/10391265/51731581-b3231d80-207b-11e9-909c-0ec4096b104f.png)

The misalignment issues are still there too (i can't test because my rpi has been down for some time, but usually they are causing crashes on arm).

Honestly if you don't want to spend too much time on fixing a pachinko game, that's fine by me, i'll let you decide if you wanna close the issue or not :)

**Comment by dinkc64** [comment]
sure - I took off some pixels, now it'll be ok :)
