### ISSUE TITLE
Compile from checkout old commit error.

### ISSUE THREAD

**Issue by tomudo** [libretro/fbalpha#131]
I checkout old commit 1 week ago and build failed. This is the some of errors shown.

src/cpu/m68k/m68kfpu.c:12:33: error: unknown type name ‘fp_reg’
 INLINE void SET_CONDITION_CODES(fp_reg reg)
                                 ^
src/cpu/m68k/m68kfpu.c: In function ‘TEST_CONDITION’:
src/cpu/m68k/m68kfpu.c:43:11: error: ‘REG_FPSR’ undeclared (first use in this function)
  int n = (REG_FPSR & FPCC_N) != 0;
           ^

**Comment by barbudreadmon** [comment]
Idk what you did wrong, however at the moment you get `src/cpu/m68k/m68kfpu.c` building failures in your log, you seriously messed up something because it's blacklisted from the build rules. Here are the instructions to build this core : 
> git clone https://github.com/libretro/fbalpha.git
> cd fbalpha
> make -f makefile.libretro

Maybe next time you post an issue give some more information (system, command used, ...), anyway good luck. Closing.
