### ISSUE TITLE
[BUG] [0.2.97.40] [RPI2] Regression with at least 2 games

### ISSUE THREAD

**Issue by nemo93** [libretro/fbalpha#138]
hi,

macross.zip is crashing at launch with the new release. It occured in the past with previous core but it had been fixed if I recall properly. 
Also irrmaze.zip (Irritating Maze) on Neo Geo does launch but display a pink screen right during the init sequence making it unplayable.

if you'd like me to test with some specific setup or rom do let me know. my setup is latest Retropie on a RPI2.

**Comment by barbudreadmon** [comment]
You got a setup issue with macross, the game is working fine. Perhaps i could help if you provide a complete log.
I'll investigate the irrmaze issue, it could be an upstream bug.

**Comment by nemo93** [comment]
I'm afraid I'll need some guidance to get you the logs. I've looked in the es_log.txt file but nothing useful there.

Also it happens that WWF: Wrestlemania (wwfmania.zip) is not launching as well (same as for macross). I'm using a proper romset rebuilt from latest Mame version hence my roms should be fine.

**Comment by barbudreadmon** [comment]
I don't know the specifics on how to get retroarch logs on retropie, ask their team, what i know : 
- macross is working fine
- irrmaze is still not working fine
- wwfmania (and every midway game) is disabled for various reasons (unable to get the driver working, probably because it is a dynarec, seems to be x86_64 only anyway + part of the code is written in c++11 which is not supported by some os)

**Comment by barbudreadmon** [comment]
Ok, iirmaze is a game that won't work if you don't set the "neogeo mode" to "DIPSWITCH" in core options. I'll have to figure out something to force this mode, whatever the user setting, for this specific game.

**Comment by barbudreadmon** [comment]
Issue with irrmaze got solved, the other 2 are not issues. I close.
