### ISSUE TITLE
FBA-Core : input/mapping issue - Super Gem Fighter Minimix

### ISSUE THREAD

**Issue by shakkalakka** [libretro/fbalpha#140]
I have noticed that the first 2 Buttons (Retropad A+B) are mapped to Volume (+/-) instead of the Fight-Buttons The Fight-Buttons are mapped to X+Y now :frowning:

All Other Games i tried are mapped correctly and work as intended. Seems to me that the default-mapping in only this particular game is bad.

my system is a intel x64 with lakka RC2.1 few Controller i tried are: XBox360 Controller, Hori Arcade Stick (FS VX) and PS4 DualShock (original)

has anyone this problem, too ?

**Comment by barbudreadmon** [comment]
Cps2 games which uses the 4th fire button as "Volume Up" should be handled properly now.

**Comment by shakkalakka** [comment]
Volume Down is still on Retropad = RB

**Comment by barbudreadmon** [comment]
Your issue was the mapping of volume +/- to B/A . But now i see you wanted to totally "unmap" them, i'll think about not assigning them a button by default when the dummy input descriptor will be available, i want to keep the ability of using those if for whatever reason someone needs it. Right now they are mapped to X/R in super gem fighter

**Comment by shakkalakka** [comment]
oh its my fault. you are right. remapping to retropadshoulder buttons seems okay (but still not perfect) for me. I hate teaching my friends: "do not that , press not that and so on".
but this maybe is an edge-scenario. I completly trust in your work and will take what i get :)
