### ISSUE TITLE
Classic and Modern control schemes are not functioning correctly

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/fbalpha#157]
When you switch from Classic to Modern in the FBA core it has no change at all to the control scheme when playing Neogeo games , this seems to of broke somewhat recently in the past few months I believe.

**Comment by barbudreadmon** [comment]
As mentioned in a few other issues, "Modern" device type for neogeo is now restricted to ffurys, kofs and samshos. At the beginning, this setting was added to mimic king of fighters gameplay from recent opus, so there is no real reason for it to do anything on other games.

I've been trying to show only available device type, perhaps with more explicit labels, depending on the game played, especially since i want to add mouse (in shooting games) & keyboard (probably for all games) support in the near future, but that's actually not an easy change, except in an ugly way i want to avoid.

**Comment by fr500** [comment]
Keyboard for all games?

**Comment by barbudreadmon** [comment]
@fr500 Current keyboard mapping is awful when playing, i would like a keyboard device type which handle some nice default. Btw, any news about the dummy input descriptors ?

**Comment by Oggom** [comment]
> Current keyboard mapping is awful when playing, i would like a keyboard device type which handle some nice default. 

...you mean the Arcade control scheme that was removed because it was "confusing"?

**Comment by barbudreadmon** [comment]
Another useful comment since i removed your personal setting for your personal configuration from this core... Sure, a misnamed controller scheme and a keyboard scheme are one and the same !

**Comment by Oggom** [comment]
@barbudreadmon While I appreciate all the work you've done for this core, I have to say it's a shame how you've turned it into a personal pet project and start throwing out sarcastic comments every time someone asks for a feature you don't like (for example https://github.com/libretro/fbalpha/issues/135#issuecomment-298233232). 

You've been asking for a mapping that works well with keyboards and that's exactly what the Arcade layout did. I told you several times if you dislike the name of it you're welcome to rename it, but instead of doing that you just axed it completely simply because you didn't feel like keeping it around.

Rather then collaborating with others and trying to figure out a solution that works for everyone you just do whatever you feel like which has me worried about the future of the core.

**Comment by fr500** [comment]
@barbudreadmon well I haven't found a way to add dummy buttons, what I've been trying to do is change the remapping GUI to work like the keymapper gui (if you haven't seen it, it's on dosbox / bluemsx).

But it ended up being very buggy and I've been busy with other things.

Providing defaults from the core would need changes to libretro, at least an additional env callback.
I also need to make the keymapper work for more than 1 player.

I'll get to it when I have some more time.

**Comment by fr500** [comment]
Ah I guess you're trying to do input with real keyboard, the best way then is create a RetroKeyboard type device and provide the game layouts internally. Also make sure to not accept any gamepad inputs when it's set to RetroKeyboard, that was the retropad keyboard defaults won't cause you any issues.

**Comment by barbudreadmon** [comment]
@Oggom No, your mapping didn't work well with keyboard. I didn't axe it "simply because i don't like it", i explained the reasons why it didn't make sense in a normal configuration, and i axed it after asking people what they thought about it, everyone agreed i should axe it, except you because you added this setting specifically for you. Rename it ? Rename it to what ? "Oggom" device type ? That's what you wanted ? So keep thinking i'm some kind of bully if you want, but stop trolling every time an issue talk about mapping, THANKS ! And yes i think i have the right to decline (or more precisely postpone) when people ask me for new feature, in whatever way i want, it's not as if i said something wrong.

@fr500 Yes that's what i was talking about

**Comment by Oggom** [comment]
> No, your mapping didn't work well with keyboard.

It worked perfectly fine every time I tried it. What problem are you having here?

> i explained the reasons why it didn't make sense in a normal configuration

Playing arcade games with a keyboard isn't a normal configuration to begin and yet here we are.

> everyone agreed i should axe it

I certainly didn't. Neither did Twinaphex who merged my PR back then.

> except you because you added this setting specifically for you

No, i did it specifically for keyboards and certain arcade controllers which is something you seem unable to wrap your head around.

> Rename it ? Rename it to what ? "Oggom" device type ? That's what you wanted ?

I want people to have the option to play the games the way they want without having to deal with multiple configuration files. I originally wanted to call it "MAME" but from what I remember the name is copyrighted so I changed it to arcade to avoid any potential trouble. You could also call it "Keyboard" if you think that works better.

> stop trolling every time an issue talk about mapping

You're the one who's acting childish and can't handle criticism. You made the decision to castrate a working feature and now you have to deal with it. Feel free to ban me from the repository if you can't act like an adult.

**Comment by barbudreadmon** [comment]
Criticism ? All i see here is someone who whine because i removed something specifically designed for himself. 

Deal with it ? The current issue had nothing to do with your device type at first, no one cares about its disappearance except you, yet you came, bringed it into the conversation and tried to justify it again by all means possible.

With current libretro api, there are better ways to handle keyboard mapping than using a retropad device type, so your old setting is still not needed. Your mapping was a mess with non qwerty keyboard anyway, same as modern/classic.

Now if the only thing you intend to contribute to this repository is this, that's really sad. And yes i suppose i'll have to do something about you if you keep going about this.

And btw, i didn't see @twinaphex disagree with the removal of the "oggom" device type.

**Comment by Oggom** [comment]
> And btw, i didn't see @twinaphex disagree with the removal of the "oggom" device type.

For the last time, this is literally the same mapping MAME uses no matter what you call it and I fail to see how using MAME as a reference for arcade emulation is a bad thing.

I explained it several times already, but input mapping for arcade emulators (which can have dozens of different mapping types even on the same hardware) is not as simple as it is for consoles where there are usually only a handful of controller types available which makes input configuration a huge hassle.

One of the main ideas of libretro and RetroArch is to have things as simple as possible to set-up for the enduser. Because of this, having an easy to change core option is the best way to handle this. One covers gamepads and modern arcade sticks while the other one covers keyboards and older arcade sticks. 

Rather than coming up with a better solution yourself you just flat out removed telling people it's not your problem. This is not something can be easily solved by just creating one or two additional configuration files.

**Comment by barbudreadmon** [comment]
Mame's default mapping is not supposed to be played with, the first thing you do when you start a game in mame is go to the osd and remap everything.

Also, for a specific game over the 6 mame cores, you'll end up with 3 or 4 different default mapping

Using their default mapping (which one ?) as some kind of reference is weird.

Anyway, as i said before your intervention, i agree we need a keyboard device type, a real one, not a joypad device type where you can't remap buttons to other keyboard keys, and sometimes, depending on your keyboard, end up being playable.
