### ISSUE TITLE
Problem With PGM Games

### ISSUE THREAD

**Issue by dragonstory** [libretro/fbalpha#158]
Hello
I just update the last FBA Core today. 02.97.44 05da761

When i try to load any PGM games, it doesn't work. The Retroarch gives that error ::
"Failed to load Content"

It was working before and it is working with MAME core. But now working any pgm games. 
I have all the correct romset with bios. Im sure it doesn't about the wrong romset.

MAC OSX High Sierra
Retroarch 1.7.6

**Comment by barbudreadmon** [comment]
Logs please

**Comment by dragonstory** [comment]
How can i get logs with Mac Osx? Please

**Comment by barbudreadmon** [comment]
Google is your friend, you just had to search "retroarch logs", is that hard to figure out ? https://docs.libretro.com/guides/generating-retroarch-logs/

There is already the fact you decided to ignore the warning `Use clrmamepro (which runs fine on linux with wine and on mac with crossover) to build valid romsets with dats from the dats directory. Don't report issues if you didn't build a valid romset.` before creating this issue.

I recommend you to stop with the lack of efforts.

**Comment by barbudreadmon** [comment]
I'll close : 
- No answer
- It's pretty obvious you got a wrong romset. FYI you are already the 4th since the beginning of this year to report "pgm not working" (first 3 were on the libretro forums), it has been a long time issue with PGM, because some FBAlpha PGM romsets are totally different from MAME's for whatever reason, the sentence `
Use clrmamepro (which runs fine on linux with wine and on mac with crossover) to build valid romsets with dats from the dats directory. Don't report issues if you didn't build a valid romset.` was actually added mainly because of PGM.

Next time follow instructions, they are done to help you and avoid reporting fake issues.
