### ISSUE TITLE
Donkey Kong (US Set 1) - high score gets corrupt, game won't work

### ISSUE THREAD

**Issue by jerrykurtz** [libretro/fbalpha#162]
The high score file seems to get corrupt, and when that happens, the game won't load.  Deleting the high score file gets it to work.

**Comment by barbudreadmon** [comment]
With the hiscore.dat from the repo ?

**Comment by barbudreadmon** [comment]
Happens with both the new and the old format. That's weird, the libretro port create a "dkong.hi" file, it seems this is the file causing issues (deleting it fix the corruption), but i don't see any such file created when playing on standalone. I'll investigate this.

**Comment by jerrykurtz** [comment]
Thank you.  I was going to put together some detailed instructions to reproduce the problem this weekend, but it appears you beat me to it.

**Comment by dinkc64** [comment]
barbudreadmon, I have a feeling you didn't get my pm before the forum died (again).  On that topic, we have a new server all set up and should be up within a day or 2.
The reason I'm writing here is regarding that the dkong.hi you sent me.  Have a look inside it, notice the config stuff in there that has nothing to do with a normal dkong.hiscore stuff?  I've seen this before, many times.  Somewhere in lr-fba you're overwritting past a memory buffer/corrupting heap, which is leading to garbage leaking into the game's ram etc.  Also, notice the reference to karnovr in there?  I have a feeling the problem with karnovr is related.  Simply going 1 character past a buffers allocated size will do this, f.ex:
char dink[3];  dink[3] = 'x';
that's because the heap is stored like this:
char dink[3];  // in memory: xxxx####
x = char, # = size of the allocated memory.  when the compilers heap system goes backwards, sorta like a link list, to keep track of things, and you've overwritten into the "allocated size" portion of the memory, it literally goes bonkers.  So, it's time to get address sanitizer out.  and possibly other tools to help with that. :)
best regards and bye for now,
- dink

**Comment by OBurgerGuy** [comment]
having this issue as well

**Comment by OBurgerGuy** [comment]
burgertime (midway) has corrupt characters as well

**Comment by barbudreadmon** [comment]
The hiscores seems ok now, sadly it didn't fix the issue in karnovr.

**Comment by OBurgerGuy** [comment]
I’ll wait until the rest of the ragged bugs are addressed, is there an eta from dev to .43?

**Comment by barbudreadmon** [comment]
Nope
