### ISSUE TITLE
Wii U sound issue

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#210]
When I play Ninja baseball bat man there is somes sound issue, choppy sound sometimes, intermittent

**Comment by barbudreadmon** [comment]
Because Irem m92 games won't run full speed on wii u, the same happens with rpi. You start running m92 fine with an overclock at 1.5Ghz. 

You probably have the same issue with : 
- irem m107
- taito f3
- svg and killbldp from pgm
- deco156

As a sidenote, i already tried writing speedhacks for those with no luck.

Closing, there is no point investigating this.
