### ISSUE TITLE
sound issues on Wii U for game D.D Crew

### ISSUE THREAD

**Issue by cecilmax** [libretro/fbalpha#212]
The game play fine overall but when the game start and the intro show on screen it is in slow motion with choppy sound. Once in the character select, the game is fine, normal speed with audio ok. Once in the game the game speed is ok but the audio is choppy sometimes..

**Comment by barbudreadmon** [comment]
Could you complete the report in https://github.com/libretro/fbalpha/issues/211 before testing other games for other issues ?

Also, while i don't mind trying to fix huge issues like the one in zeroteam, i won't fix anything related to choppy audio, because it is either the hardware struggling with the emulation (see https://github.com/libretro/fbalpha/issues/210) or the platform having some issues with the audio implementation (see https://github.com/libretro/fbalpha/issues/155). For the second case, you can try lowering audio settings in the core option.

**Comment by cecilmax** [comment]
Ok because I just found it have also graphics problem, please reopen it and I will post a screenshot..

**Comment by cecilmax** [comment]
Here is the screenshot, you can see the graphic issue.

https://pasteboard.co/HmqNZv7.jpg

**Comment by dinkc64** [comment]
ouch, looks like the scroll registers are getting borked by a le/be issue.  I could be wrong.

**Comment by dinkc64** [comment]
After we get raiden2/zero team 100% I will turn focus on to this game.  Please be patient!

**Comment by cecilmax** [comment]
Thanks :) very appreciated :)

**Comment by barbudreadmon** [comment]
Could you take a look at https://raw.githubusercontent.com/libretro/fbalpha/master/gamelist.txt and test some other games running on System 16 and System 18 ? The 2 systems share common code, i think it will help figuring out where is the issue.

**Comment by cecilmax** [comment]
Ok, I will let you know the results tonight.

**Comment by cecilmax** [comment]
Here is the results:
System16:
Golden axe, 100% ok
Altered beast, 100% ok
Tetris: graphics ok, sound: choppy sound when playing

System 18:
Alien storm: game load, I insert coin, select player, now the intro start, graphics still ok but animation is slow and sound choppy just like d d crew intro, once in the game, sound is ok and gameplay is it at good speed.

Moonwalk: 100% ok

**Comment by barbudreadmon** [comment]
Could you give a try to "cltchitr" ? I'm especially interested in this one, it shares more common code with ddcrew than the others.

**Comment by cecilmax** [comment]
Just test it, play for 5-10 min and 100% ok

**Comment by barbudreadmon** [comment]
Which means the endian issue is probably not in the `System18Bank40000Init()` call, but could be in the `sega_315_5195` calls, could you try outrun and shangon ?

**Comment by barbudreadmon** [comment]
Hmmm that's kinda weird, do you have the same issue with the clone `ddcrewd` ?

**Comment by cecilmax** [comment]
Yes, same issue with the clone.

**Comment by cecilmax** [comment]
Alien storm only seem to have the same issue except for graphics

**Comment by barbudreadmon** [comment]
Well, the choppy sound is most likely related to a performance issue, not a big endian issue, i could be wrong though. Let's hope @dinkc64 will be able to find what is causing this issue (personally i have no clue, i thought you would experience similar glitches in games where the code is extremely similar, but it doesn't seem to be the case).

**Comment by cecilmax** [comment]
Ok, Im always available to do more tests :)

**Comment by cecilmax** [comment]
I just test desertbr game, I notice when the game start it show a scrolling screen of ocean for 2-3 sec and it was slowed down and sound cut a little bit, once the player can start moving the character, everything is ok.

It is look like it is related with a performance of system 18 when the game start...

**Comment by barbudreadmon** [comment]
Here's a message from dink : 
> sega system 18 is basically system 16 with a couple more system 16-style video layers and also a sega megadrive(genesis) vdp chip.  this megadrive vdp is very resource intense.  I noticed in D.D. Crew it enables the genesis vdp during the attract mode sequence a few times, and that's probably where you notice the audio glitches, because the cpu can't keep up with everything.  During the gameplay, it doesn't use the megadrive vdp at all, so that's why the gameplay is fine.
I noticed and fixed a few endian issues in the megadrive vdp, I'm not sure if it will help with the slowdown at all, but it might fix the graphics issues at least.  Right now it's just a test, if the graphics issues still exist (like in the picture you posted of ddcrew's attract), I'll try something different.

Let us know how it turns out.

**Comment by cecilmax** [comment]
Ok I just test it, the graphic glitch is fixed and the sound at the intro is better but not perfect, it is still not at normal speed if I compare it to video on youtube when I watch a long play video of the game.

I notice another issue: when I insert let say 3 coins and used one to start the game, when I choose to close content or even restart retroarch, and reload the game again, it still have 2 coins left...

**Comment by cecilmax** [comment]
I just test alien storm and it have the same coins glitch and still be in slow motion animation after selected a character, once the game start, it is at normal speed.

**Comment by barbudreadmon** [comment]
Does the coin issue happen in fba windows ? It seems to be stored in the nvram we load/save at init/exit, but fba standalone should be doing exactly the same.

**Comment by dinkc64** [comment]
This is normal in a lot of Sega System 16,18 games - they save the amount of coins inserted in nvram so if the power goes out, the person can still play their games when it comes back on.  It's kinda annoying for emulation, though :)  Back in the day I bet it made some people happy..

**Comment by cecilmax** [comment]
Ok loll well if it is normal, maybe we can focus to try optimize the speed in the intros of both games

**Comment by barbudreadmon** [comment]
@dinkc64 thanks for the information :)

@cecilmax Sadly, i don't think we can do anything about the intro, wii u just lacks the power, and i think the important thing is gameplay anyway.

**Comment by cecilmax** [comment]
Oh ok, at least we fixed the graphics :)

**Comment by cecilmax** [comment]
Maybe if we skip somes frames in the intro ? That would help ?

**Comment by barbudreadmon** [comment]
That's too much work for an intro, keep in mind that those games run fine on a 40$ computer like the raspberry. Spending time on this wouldn't help a lot of people.

if the graphics issue is fixed, i'm closing.

**Comment by cecilmax** [comment]
Ok, what is the best machine for mame games to make sur every game will run well ? Xbox1 or pi 3 ? Else ?

**Comment by barbudreadmon** [comment]
Higher cpu frequency is better for emulation, so i would say latest raspberry (rpi3b+ is 1400Mhz, Xbox is 733Mhz).

**Comment by cecilmax** [comment]
Ok because wii u is at 1.24ghz why it can rum game properly ? 1.4 is not so far of 1.24 :)

**Comment by barbudreadmon** [comment]
I often see games where a few Mhz can make a difference, so 150Mhz can be a lot, but i don't think that's the only issue here : 
* the big endian architecture is probably somehow affecting performance since we are constantly converting data from a format to another.
* comparing architecture is kinda hard, but i kinda remember powerpc (the wii u cpu) lost against x86 because of his low efficiency (at same cpu frequency, it would consume more power to achieve less operations). On the other side, arm is all about efficiency while not targeting extreme performances, besides mobile phones and raspberry, it's also what is used in ps4 or switch.

So yes, slowdowns on wii u totally make sense to me, and that's why i never had any interest in turning mine into an emulation computer, things would be different if it had the same powerpc as the ps3 (while it is 6 years older, its powerpc is at 3.2Ghz)

**Comment by cecilmax** [comment]
Ok :) I think nintendo switch will be good too ? Do you plan to release for switch ? I wondsr if switch is low or big endian ?

**Comment by barbudreadmon** [comment]
> I wondsr if switch is low or big endian ?

As i already explained, big endian is basically a dead thing.

I think there is already a switch port of retroarch, but multi-core architecture with low cpu freq and 3D gpu will obviously sucks for single thread 2D emulation, psvita with its 2Ghz cpu would be a better choice as a handheld for fba.
