### ISSUE TITLE
Dragon Ball Z & Dragon Ball Z 2: Super Battle Colors mess up on Wii U

### ISSUE THREAD

**Issue by MarioSonicBusserA** [libretro/fbalpha#227]
as the titles says 
both of the Banpresto DBZ games when i load them up on the FBalpha core on Wii U RetroArch
the game works fine but the colors are mess up and not accurate to the actual arcade game  
i tried both cores with results of
FBalpha least core updated = game works but colors are all over the place 
FBalpha 2012 = Failed to load content 
is it my roms that i have or something else since i tired downloading other roms and results are the same

**Comment by barbudreadmon** [comment]
It is probably a big endian issue. I'll let @dinkc64 know, perhaps this one doesn't require too much work to be fixed.

**Comment by barbudreadmon** [comment]
@MarioSonicBusserA Let me know if the latest commit fixed your issue. If it doesn't, please post a screenshot.

**Comment by MarioSonicBusserA** [comment]
issue not fixed yet

**Comment by barbudreadmon** [comment]
@MarioSonicBusserA would be nice if you actually answered instead of closing/reopening the issue...

**Comment by MarioSonicBusserA** [comment]
Sorry i have been busy with stuff and trying to get screenshots of the way the game looks
But
![dbz2-180814-091218](https://user-images.githubusercontent.com/40992017/44130105-90f33ef6-a011-11e8-854b-874d54d40d04.png)
![dbz-180814-091012](https://user-images.githubusercontent.com/40992017/44130106-910c8668-a011-11e8-8716-18f2c40024a3.png) 
yeah so i better off tell a description of the game look
Sprites look like normal like fighters and background characters are fine too but the actual backgrounds 
are still have colors all over the place but its getting better

**Comment by barbudreadmon** [comment]
Solving issues for a dead architecture is already a bother, it is worse if you can't provide screenshots either...

**Comment by barbudreadmon** [comment]
@twinpahex Closing because this issue is going nowhere. Honestly, at this point, could we just remove the wiiu build from the buildbot ? Reasons : 
- WiiU's cpu has too crappy performance to run most of the game in this core
- This core was never written to run on big endian architecture, and patching it is too much work and pointless for the future : **big endian is dead**
- Until now, all people who reported WiiU issues did something that seriously pissed me off : no answering nor providing sufficient informations, starting the issue by "so i downloaded random roms on internet and they didn't work", or polluting unrelated issues with their own.

I'm not a WiiU hater, far from that (i own one), just stating the facts : i can't recommend it as a device to run fbalpha, there are better and cheaper options (even the first rpi probably run this core better).
