### ISSUE TITLE
Make subsystem load content menu present after load core

### ISSUE THREAD

**Issue by zach-morris** [libretro/fbalpha#235]
Attempting to initially load a Neo Geo CD from the GUI fails.

Steps were as follows:
Load Core FBAlpha (build 6f85b5d)
Select Load Content, select Neo Geo CD ISO (League Bowling.iso)

Result:
Load Fails

Log:
```
Zs-MacBook-Pro:~ XXX$ /Applications/RetroArch.app/Contents/MacOS/RetroArch
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES 
Built: May  4 2018
[INFO] Version: 1.7.3
[INFO] =================================================
...
[INFO] Updating firmware status for: /Applications/RetroArch.app/Contents/Resources/cores/fbalpha_libretro.dylib on /Users/XXX/Documents/RetroArch/system
[INFO] Using content: /Users/XXX/Downloads/neo_cd_iso/League Bowling.iso.
[...
[ERROR] Failed to load content.
```

Note however after that initial load failure, now there are a number of subsystem load content options in the XMB
![XMB](https://i.imgur.com/PJylOQ1.png)

Now I select the "Load NeoGeo CD" option, and choose the same iso.  Then I get a "Start Neo Geo CD ?" Option, and I hit OK, and it fails again (with same general Error).  Then I can again select Load NeoGeo CD and choose the iso and then Start Neo Geo CD and then it works.

Suggestion is to make the Load Subsystem options available after I initially 'Load Core'.  I'm unsure why the load fails once and then works the second time.

**Comment by barbudreadmon** [comment]
AFAIK, retroarch doesn't allow to load subsystems through the gui, so that's not a fbalpha issue. @fr500 could confirm ?

**Comment by barbudreadmon** [comment]
@fr500 Thanks, i guess this is low priority considering fbalpha is the only core using subsystems that way ?

**Comment by barbudreadmon** [comment]
> I'm guessing it's not possible to determine the subsystem during loading either?

By definition, retroarch subsystems are not something you "determine during loading", but i guess that's not what you meant : you meant determine if it is a neogeocd game when loading through normal load content ? That won't happen, that's bad design leading to awful issues : if i tag iso/bin/cue as loadable content by the core, and a normal zipped arcade rom contains a file with such an extension (100% sure there are tons of bin files, don't know about the 2 others), it will decompress the zip file and read the iso/bin/cue file instead of reading the zip file as a whole, leading to the game not working. I encountered this issue while trying to implement the loading of mame naomi roms in reicast...

Also, using this core to play neogeo cd games is a waste of time atm : the only exclusive (samourai showdown rpg) is not working, neither the enhanced audio. So basically the only thing you can do is playing games already available with **better graphics** and **no loading time** on normal neogeo AES/MVS. No point except if you are a masochist.

And while i guess it would be nice for the sake of completion to have fully working neogeo cd support in this core, i can't find the time and motivation.

I'm closing this issue, since the original issue is not a fbalpha issue, and other neogeo cd issues are treated there : https://github.com/libretro/fbalpha/issues/4.

**Comment by zach-morris** [comment]
Fair enough on your points.  While this example was specific to Neo Geo CD, it was meant to be general for all subsystems that FBAlpha supports.

**Comment by fr500** [comment]
@barbudreadmon not really about priorities, but to achieve it you have to touch the main retro_implementation which is kind of delicate. I tried, raised a few questions and the answer was "I don't know about subsystems, ask maister" so I gave up.

**Comment by fr500** [comment]
Ok so basically what should happen is something like this:
https://github.com/libretro/RetroArch/blob/0f4744bed7cdb2f86e0a533f9ccdc263fa3a270b/dynamic.c#L179

The subsystem info would need to be set in retro_system_info, RA should sets subsystems at that point in time.

**Comment by barbudreadmon** [comment]
> Fair enough on your points. While this example was specific to Neo Geo CD, it was meant to be general for all subsystems that FBAlpha supports.

That's totally impossible for other systems, since an arcade rom can share the same filename than a md (or whatever) rom. MAME and FBA are filename based for initializing a game.

**Comment by fr500** [comment]
RA should fix this anyway, it's not about the case.
For sameboy the same problem exists, you have to load one game before loading the subsystem you want and so forth

Also the menu should be refined

In my mind it would have been something like this

![image](https://user-images.githubusercontent.com/1721040/44941809-de267100-ad6a-11e8-87cc-851f3ad96e03.png)
