### ISSUE TITLE
[RPI2] Performance issues with some games

### ISSUE THREAD

**Issue by thomasgoldstein** [libretro/fbalpha#36]
I'm having performance issues on my Raspberry Pi 2 running RetroPie, with certain games only. I'm not sure whether those problems come from the original FBA or from libretro ports, but the older FBA libretro port has the same issues.

Many games play very nicely (Neo Geo games, CPS games, etc), but other games that are much simpler and older run very poorly, like Data East or Sega games. Crude Buster is a rather good example of that, but there are many others. Mame4all (libretro or not) plays this game at full speed on the same machine, even though Mame is not known for its speed.

Are these performances issues known? If not, do you need a list of games affected?
Do these problems come from upstream (maybe some driver-specific issues)?

Thanks.

**Comment by barbudreadmon** [comment]
Those seems to be m68k games, mame4all probably runs them faster because he runs them through cyclone (an arm dynarec for m68k). I've been wanting to port cyclone to libretro-fba as a core option (i tried at https://github.com/barbudreadmon/libretro-fba but games would reboot after a few seconds), but i'm a rookie at writing emulation stuff. Don't expect any progress except if @twinaphex or any other veteran give it a try.

**Comment by barbudreadmon** [comment]
To answer your question, yes, like every fba game having slowdown on rpi/rpi2, those issues comes from upstream, because fba is not targeted to arm cpu.

**Comment by thomasgoldstein** [comment]
Thanks for your answer. I'm already glad for all your work so far and don't expect more, I was mostly curious.

**Comment by barbudreadmon** [comment]
m68k games should run a little faster with https://github.com/libretro/fbalpha/commit/b895a6829f260cb1f9d36c2bcc53622a83b65018
And rpi3 have been out for almost one year, i have no speed issues with those games (i didn't have speed issues at the time you wrote this either), so i'm closing.
