### ISSUE TITLE
When hotkey and add coin key are same button, can't add coin in some games

### ISSUE THREAD

**Issue by dankcushions** [libretro/fbalpha#44]
If your hotkey and insert coin are the same button (eg 'select' button on a SNES clone controller), many games will not register the insert coin. I've not got any specific examples but I tried a bunch of Cave shooters last night and had the issue. I imagine it happens in Street Fighter II as that seems to have the issue in other mame/fba cores:
https://github.com/libretro/mame2003-libretro/issues/8
https://github.com/libretro/fba-libretro/issues/46
https://github.com/libretro/imame4all-libretro/issues/9
- for that reason I logged it as a retroarch issue also:
https://github.com/libretro/RetroArch/issues/2230

However we're still not entirely sure where the fault lies (with the cores or the libretro input libraries), so thought I'd log it here as well, just in case anyone has any suggestions :) Cheers!

**Comment by objectchris** [comment]
This is resolved for Retropie users in patch https://github.com/RetroPie/RetroPie-Setup/pull/1278
The same or similar fix would need to applied to Retroarch to resolve this issue.

**Comment by mikeh482** [comment]
For anyone still experiencing this issue, I discovered an easy workaround that works for me. In RetroArch menu, make the START button your hotkey enable. This allows the select button to work for adding credits/coins in Mame/FBA, and the start button still functions as the start button for games, despite also being the hotkey enable button. 

I believe the original problem, which only affected certain arcade games, was because those games used different button timing to register coins (the way they were originally programmed), and that coin timing is what would cause the hotkey to block the coin button from being registered on those specific games. The start button for those (and all) games doesn’t appear to use the same timing as the coin button, and therefore is unaffected by also being the hotkey enable button. 

I’ve tested the START button as the hotkey enabler in many different cores and haven’t had any problems. In cores where the start button pauses the game, it saves the states in a paused state, or enters the menu in a paused state, so when loading a state or exiting the menu, the game resumes in a paused state, which is nice, and allows me to start play when I am ready, and not immediate when loading a state or exiting menu. 

I’m using the android version of RetroArch. Curious if this also works on PC, RetroPie, etc, but I assume it does.
